version: '3'
services:
  snmptrapd:
    build: ./snmptrapd
    ports:
      - "8162:8162/udp"
    links:
      - fluentd
    extra_hosts:
      - "jm00z0test1:192.168.27.135"
      - "jc02z1vyos1:192.168.27.100"
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: httpd.access

  fluentd:
    build: ./fluentd
    # volumes:
    #   - ./fluentd/conf:/fluentd/etc
    # ports:
      # - "24224:24224"
      # - "514:514/udp"
    links:
      - mongo
      # - influxdb
    # extra_hosts:
    #   - "snmpd:192.168.27.171"
      # - "jm00z0test1:192.168.27.135"
      # - "jc02z1vyos1:192.168.27.100"

  # influxdb:
  #   build: ./influxdb
  #   restart: always
  
  # chronograf:
  #   image: chronograf:alpine
  #   restart: always
  #   links:
  #     - influxdb
  #   ports:
  #     - "8888:8888"
  
  mongo:
    image: mongo
    restart: always
    # volumes:
    #   - "./mongo:/data"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example

  ### snmptrap-exporter
  snmptrap-exporter:
    build: ./snmptrap-exporter
    # container_name: snmptrap-exporter
    ports: 
      - 8000:8000
    restart: always

  #### prometheus compose is below (for test) .
  prometheus:
    # image: prom/prometheus
    build: ./prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/data:/prometheus/data
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: always

